
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 200, 88, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("SET YOUR ALARM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 50, 480, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 140, 60, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 140, 70, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("hr");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 110, 30, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("min");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 110, 25, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(310, 150, 70, 30);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 200, 64, 30);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 200, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   Thread alarm = new Thread()
   {
     public void run()
     {
         
         try {
             for(;;){
                 int i,j;
           Date date= new Date();
           SimpleDateFormat format= new SimpleDateFormat("h");
           SimpleDateFormat format1= new SimpleDateFormat("mm");
           SimpleDateFormat format2= new SimpleDateFormat("ss");
           SimpleDateFormat format3= new SimpleDateFormat("a");
           String currenthr=format.format(date);
           String currentmin=format1.format(date);
           String currentsec=format2.format(date);
           String hr=jTextField1.getText();
           String mn=jTextField2.getText();
           String amorpm=format3.format(date);
           int input_hr=Integer.parseInt(hr);
           int input_min= Integer.parseInt(mn);
           int current_hr=Integer.parseInt(currenthr);
           int current_min=Integer.parseInt(currentmin);
           int current_sec=Integer.parseInt(currentsec);
           String comboselect=(String)jComboBox1.getSelectedItem(); 
          
          if(amorpm=="AM")
          {
             i=0;
          }
          else
          {
             i=1;
          }
          if(comboselect=="AM")
          {
             j=0;
          }
          else
          {
            j=1;   
          }

            if(i == j)
          {
              if(input_hr<current_hr)
              {
                 int min1=60-current_min+input_min;
                 int hr1=(24+input_hr-current_hr-1)+(min1/60);
                 min1=min1%60;
               jLabel1.setText("Alarm is set for "+hr1+" hr "+min1+" min"+" from now"); 
               
               if(current_hr==input_hr && current_min==input_min)
                  {
                     jLabel1.setText("Wake Up");  
                       playmusic("E:\\Music\\Nepali\\Lok\\Baja\\New Panchebaja Song 2074 पन्चेबाजा गीत Makur Makur Ghur By Devi Gharti  Prakash Saput.mp3");
                                          
                     if(current_min==current_min+1)
                     {
                      dispose();   
                     }
                  }
              }
              else if(input_hr==current_hr)
              {
                 if(input_min<current_min)
                 {
                     int ii=23;
                 jLabel1.setText("Alarm is set for "+ii+" hr "+(60-current_min)+" min"+" from now"); 
                 if(current_hr==input_hr && current_min==input_min)
                  {
                     jLabel1.setText("Wake Up");
                      playmusic("C:\\Users\\Rajan\\Downloads\\Music\\Danger Alarm Sound Effect.wav");
                  }
                 }
                 else
                 {
                     int ii=0;
                   jLabel1.setText("Alarm is set for "+ii+" hr "+(input_min-current_min)+" min"+" from now");   
                 }
                  if(current_hr==input_hr && current_min==input_min)
                  {
                     jLabel1.setText("Wake Up");
                       playmusic("E:\\Music\\English\\#8 Get Low Fast and Furious 7.mp3");
                  }
              }
              else
              {
                 if(input_hr==12)
                 {
                 input_hr+=12;
                 }
                 
                 int min1=60-current_min+input_min;
                 int hr1=(input_hr-(current_hr+1))+(min1/60);
                 min1=min1%60;
                 jLabel1.setText("Alarm1 is set for "+hr1+" hr "+min1+" min "+" from now");  
                 
                 if(current_hr==input_hr && current_min==input_min)
                  {
                     jLabel1.setText("Wake Up");
                     playmusic("C:\\Users\\Rajan\\Downloads\\Music\\Danger Alarm Sound Effect.wav");
                     if(current_min==current_min+1)
                     {
                      dispose();   
                     }
                  }
              }
             
          }
            else
            {
                int hr1;
                 int min1=60-current_min+input_min;
                 if(input_hr==12)
                 {
                     if(current_min==0 && input_min==0)
                     {
                       hr1=(input_hr-current_hr);
                     }
                     else
                     {
                       hr1=(input_hr-current_hr-1)+(min1/60);       
                     }
                 }
                 else
                 {
                    hr1=(12+input_hr-current_hr-1)+(min1/60);
                 }
                 min1=min1%60;
                 jLabel1.setText("Alarm is set for "+hr1+" hr "+min1+" min "+" from now");
                 if(current_hr==input_hr && current_min==input_min)
                  {
                     jLabel1.setText("Wake Up");
                      playmusic("C:\\Users\\Rajan\\Downloads\\Music\\Danger Alarm Sound Effect.wav");
                     if(current_min==current_min+1)
                     {
                      dispose();   
                     }
                  }
            }
             sleep(1000);
         }  
         } catch (InterruptedException ex) {
             Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
         }
          
     }
     
   };
  
   alarm.start();
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      if(jComboBox1.getSelectedItem()=="AM")
      {
          
      }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextField1.setText("");
       jTextField2.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                index ind= new index();
                ind.setVisible(true);
                ind.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                ind.setSize(636,334);
            }
        });
    }
     public static void playmusic(String filepath)
   {
      InputStream music;
      try
      {
          music= new FileInputStream(new File(filepath));
          AudioStream audio= new AudioStream(music);
          AudioPlayer.player.start(audio);
      }
      catch(Exception e)
      {
        JOptionPane.showMessageDialog(null, "Exception Cought");
      }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
