
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        digitalclock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 5)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Display Time");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 150, 300, 60);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Display day");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 70, 240, 60);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Display date ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 230, 330, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 550, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void digitalclock()
    {
        
        Thread clock = new Thread()
        {
           public void run()
           {
               try {
                   for(;;){
                     Calendar c= Calendar.getInstance();
                     Date date=new Date();

                     SimpleDateFormat format1= new SimpleDateFormat("HH:mm:ss  a");
                     SimpleDateFormat format2= new SimpleDateFormat("EEEE");
                     SimpleDateFormat format3= new SimpleDateFormat("YYYY:MM:dd");
                     jLabel1.setText(format1.format(date)); 
                     jLabel1.setFont(new Font("Ariel",Font.BOLD,48));
                    
                     
                     jLabel2.setText(format2.format(date)); 
                     jLabel2.setFont(new Font("Ariel",Font.BOLD,38));
                         
                     
                     jLabel3.setText(format3.format(date));
                     jLabel3.setFont(new Font("Ariel",Font.BOLD,28));
                     sleep(1000);
                   }
               } catch (InterruptedException ex) {
                  ex.printStackTrace();
               }  
           }
        };
        clock.start();
    }   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                index ind= new index();
                ind.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                ind.setVisible(true);
                ind.setSize(570,420);
                ind.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
